### PR TITLE
Keyword-only function arguments

### PR DESCRIPTION
**Pull request by delirious-lettuce**
This PR is just a little experiment to see if I could get rid of (most of) the globals and use Python 3's keyword-only function arguments to make the function calls clearer.

* Reorder imports ([PEP8: standard, third-party, local](http://pep8.org/#imports))
* Add `os` and `tempfile` imports
* Remove `json` import
* Remove `REPORT_PATH` global in favor of `tempfile.gettempdir()` (OS specific temporary directories)
* Use keyword-only function arguments instead of globals
* Use `r.json()` instead of `json.loads(r.text)`
* Use lowercase variable names inside of functions
* Use `try/except/else`
* Use ** unpacking in `str.format` (where applicable)
* Create paths using `os.path.join` (OS specific separators)
* Parse command-line arguments inside a separate function (less code in `main`)

### CODE REVIEW

**Comment by 0x4D31** [comment]
@delirious-lettuce Thank you so much for the PR. Not sure why I used those globals instead of passing them as function args!! :man_facepalming:
Anyway, I think it's better to replace your keyword-only args with normal keyword args to support both Python 2 & 3. Any thoughts?

**Comment by 0x4D31** [comment]
@delirious-lettuce And just saw that slackclient doesn't support Python 3, so please replace the keyword-only args so I can merge the PR.

**Comment by delirious-lettuce** [comment]
@0x4D31 ,

Sorry for the delayed response, just saw your message now.

Ya, if supporting Python 2 is a necessity than keyword-only args are pretty much out (there is a Python 2 workaround I just read about in "Effective Python" but it is quite verbose). I made a bit of an assumption that it was Python 3 only because of the print's as functions without `from __future__ import print_function`. I know you aren't actually using (at least yet) any of the print function's args like `end` so Python 2 currently just somewhat ignores the brackets.

I think I can just remove the `*, ` from each function declaration and that should fix the keyword-only issue ~~but did you want me to add `from __future__ import print_function` as well?~~ (I'll just leave the import one for now, logging off for the night!)

**Comment by 0x4D31** [comment]
@delirious-lettuce Awesome. Thanks for the quick response. I just tested it and it seems OK.

**Comment by 0x4D31** [comment]
Ah F**, mistakenly closed the PR

**Pull request merged**
